### ISSUE TITLE
How to read tween easing properties from Publisher.cpp

### ISSUE THREAD

**Issue by Ch1pStar** [pixijs/animate-extension#65]
I'm trying to change the export format, specifically to export tweens as first, last frame and easing, instead of frame by frame. 
I've been digging through the c++ code, but there aren't any references to easings, hopefully someone in here knows the API better.
My guess is it has something to do with the DOM::PITimeline structure that is passed to the publish method, but I cant find any definitions for it and from what I understand it is created before the extension code

**Comment by bigtimebuddy** [comment]
I think we need to update to the latest Animate custom publish doc API library which provides supports for describing tweens instead of converting to frames.

**Comment by Ch1pStar** [comment]
Ouch, sounds scary! Would that mean rewriting the whole publisher code?

**Comment by bigtimebuddy** [comment]
Yup. I don’t think it’s a totally rewrite, but it’s some work.
