### ISSUE TITLE
how to access the ticker from animate?

### ISSUE THREAD

**Issue by trufo2** [pixijs/animate-extension#85]
I'm trying to animate a blur on an instance of an MC:

const blurFilter1 = new PIXI.filters.BlurFilter();
this.mario_01.filters = [blurFilter1];
let count = 0;
PIXI.ticker.add(() => {
    count += 0.005;
    const blurAmount = Math.cos(count);
    blurFilter1.blur = 20 * (blurAmount);
});

But I don't know how to access the pixiAnimate ticker. Could someone point me in the right direction?

**Comment by andrewstart** [comment]
This would be a question about the [runtime](https://github.com/pixijs/animate/), not the extension, but Movieclips just animate using PixiJS's shared ticker: `PIXI.Ticker.shared`.

**Comment by trufo2** [comment]
That works. Thanks.
